FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Incluir()
        {
            return View();
        }


        [HttpPost]
        public JsonResult Incluir(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                if(bo.PesqBeneficiarioCPF(model.Cpf, model.IdCliente))
                {
                    Response.StatusCode = 400;
                    return Json("O CPF informado já está cadastrado como beneficiário para esse cliente.");
                }
                bo.Incluir(new Beneficiario()
                {
                   Cpf = model.Cpf,
                   Nome = model.Nome,
                   IdCliente = model.IdCliente,
                });
                return Json( new { Message = "Cadastro efetuado com sucesso"});
            }
        }
        [HttpPost]
        public JsonResult Listar(long IdCliente)
        {
            BoBeneficiario bo = new BoBeneficiario();
            List<Beneficiario> LstBeneficiarios = bo.Listar(IdCliente);
            List<BeneficiarioModel> LstBeneficiariosModel = null;

            if (LstBeneficiarios != null)
            {
                LstBeneficiariosModel = (from b in LstBeneficiarios
                                         select new BeneficiarioModel
                                         {
                                             Id = b.Id,
                                             Cpf = b.Cpf,
                                             Nome = b.Nome,
                                             IdCliente = b.IdCliente
                                         }).ToList();

            }

            return Json(new { Result = "OK", Records = LstBeneficiariosModel, TotalRecordCount = LstBeneficiariosModel?.Count() ?? 0 });
        }

        [HttpPost]
        public JsonResult Alterar(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                if (bo.PesqBeneficiarioCPF(model.Cpf, model.IdCliente))
                {
                    Response.StatusCode = 400;
                    return Json("O CPF informado já está cadastrado como beneficiário para esse cliente.");
                }
                bo.Alterar(new Beneficiario()
                {
                    Cpf = model.Cpf,
                    Nome = model.Nome,
                    Id = model.Id,
                });
                return Json(new { Message = "Alteração efetuada com sucesso" });
            }

        }

        [HttpPost]
        public JsonResult Remover(long Id)
        {
            BoBeneficiario bo = new BoBeneficiario();
            bo.Remover(Id);
            return Json(new { Message = "Remoção efetuada com sucesso" });
        }


    }
}

FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(ClienteModel model)
        {
            BoCliente bo = new BoCliente();
            
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                if (bo.VerificarExistencia(model.Cpf))
                {
                    Response.StatusCode = 400;
                    return Json("O CPF informado já está cadastrado.");
                }

                model.Id = bo.Incluir(new Cliente()
                {                    
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Cpf = model.Cpf,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone
                });


                return Json(new { Message = "Cadastro efetuado com sucesso", id = model.Id });
            }
        }

        [HttpPost]
        public JsonResult Alterar(ClienteModel model)
        {
            BoCliente bo = new BoCliente();
       
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                if (bo.VerificarExistencia(model.Cpf))
                {
                    Response.StatusCode = 400;
                    return Json("O CPF informado já está cadastrado.");
                }
                bo.Alterar(new Cliente()
                {
                    Id = model.Id,
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Cpf = model.Cpf,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone
                });
                               
                return Json("Cadastro alterado com sucesso");
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoCliente bo = new BoCliente();
            Cliente cliente = bo.Consultar(id);
            Models.ClienteModel model = null;

            if (cliente != null)
            {
                model = new ClienteModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Cpf= cliente.Cpf,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone
                };

            
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = new BoCliente().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Views/Cliente/Alterar.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel
@{
    ViewBag.Title = "Alterar Cliente";
}
@section scripts{
    <script>
        var urlPost = '@Url.Action("Alterar", "Cliente", new { area = "" })';
        var urlGetBeneficiarios = '@Url.Action("Listar", "Beneficiario", new { area = "" })';
        var urlAlterarBeneficiario = '@Url.Action("Alterar", "Beneficiario", new { area = "" })';
        var urlInserirBeneficiario = '@Url.Action("Incluir", "Beneficiario", new { area = "" })';
        var urlRemoverBeneficiario = '@Url.Action("Remover", "Beneficiario", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));
        var urlRetorno = '@Url.Action("Index", "Cliente", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/altClientes")
    @Scripts.Render("~/bundles/altBeneficiarios")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/Views/Cliente/Forms.cshtml
<form id="formCadastro" method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nome">Nome:</label>
                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Sobrenome">Sobrenome:</label>
                <input required="required" type="text" class="form-control" id="Sobrenome" name="Sobrenome" placeholder="Ex.: da Silva" maxlength="255">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Cpf">CPF:</label>
                <input required="required" type="text" class="form-control" id="Cpf" name="Cpf" placeholder="Ex.: 010.010.010-10" maxlength="14">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nacionalidade">Nacionalidade:</label>
                <input required="required" type="text" class="form-control" id="Nacionalidade" name="Nacionalidade" placeholder="Ex.: brasileira" maxlength="50">
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="CEP">CEP:</label>
                <input required="required" type="text" class="form-control" id="CEP" name="CEP" placeholder="Ex.: 01011-100" maxlength="9">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Estado">Estado:</label>
                <select required="required" id="Estado" class="form-control" name="Estado">
                    <option value="">Selecione</option>
                    <option value="SP">São Paulo</option>
                    <option value="PE">Pernambuco</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Cidade">Cidade:</label>
                <input required="required" type="text" class="form-control" id="Cidade" name="Cidade" maxlength="50" placeholder="Ex.: São Paulo">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="Logradouro">Logradouro:</label>
                <input required="required" type="text" class="form-control" id="Logradouro" name="Logradouro" placeholder="Ex.: Rua Boa Vista 253" maxlength="500">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Email">E-mail:</label>
                <input required="required" type="text" class="form-control" id="Email" name="Email" placeholder="Ex.: email@email.com" maxlength="2079">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Telefone">Telefone:</label>
                <input required="required" type="tel" class="form-control" id="Telefone" name="Telefone" placeholder="Ex.: (11) 2020-3030" maxlength="15">
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-6">
            <div class="pull-left">
                <button id="btnBeneficiarios" class="btn btn-default">Beneficiários</button>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="pull-right">
                <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-sm btn-danger" })
            </div>
        </div>
    </div>

</form>

<div id="modalBeneficiarios" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Beneficiários</h4>
            </div>
            <div class="modal-body">
                <p id="alertas"></p>
                <div class="row">
                    <div class="col-md-5">
                        <label for="Cpf">CPF:</label>
                        <input required="required" type="text" class="form-control" id="cpfBeneficiario" name="Cpf" placeholder="Ex.: 010.010.010-10" maxlength="14">
                    </div>
                    <div class="col-md-5">
                        <label for="Nome">Nome:</label>
                        <input required="required" type="text" class="form-control" id="nomeBeneficiario" name="Nome" placeholder="Ex.: João" maxlength="50">
                    </div>
                    <div class="col-md-2" syle="height:100%">
                        <label>
                            <p>&nbsp;<p>
                                <button id="btnAdicionarBeneficiario" class="btn btn-sm btn-success">Incluir</button>
                                <button id="btnSalvarBeneficiario" style="display:none" class="btn btn-sm btn-success">Salvar</button>
                                <input id="editItemID" type="hidden" value="" />
                        </label>
                    </div>
                </div>
                <table id="gridBeneficiarios" class="table">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>CPF</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div> 

FI.WebAtividadeEntrevista/Views/Cliente/Incluir.cshtml
@{
    ViewBag.Title = "Cadastrar Cliente";
}
@section scripts{
    <script>
        var urlPost = '@Url.Action("Incluir", "Cliente", new { area = "" })';
        var urlPostBeneficiario = '@Url.Action("Incluir", "Beneficiario", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/clientes")
    @Scripts.Render("~/bundles/beneficiarios")

}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}
@section scripts{
    <script>
    var urlAlteracao = '@Url.Action("Alterar", "Cliente", new { area = "" })';
    var urlClienteList = '@Url.Action("ClienteList", "Cliente", new { area = "" })';

    </script>
    @Scripts.Render("~/bundles/listClientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.ActionLink("Novo Cliente", "Incluir", "Cliente", new { }, new { @class = "btn btn-sm btn-primary pull-right" })
<table id="gridClientes" class="table"></table>